monolog:
    channels: ["sms", "alarm_zabbix", "bitrix_create", "one_s"]
    handlers:
        sms:
            type: stream
            path: "%kernel.logs_dir%/sms.log"
            channels: ["sms"]
        alarm_zabbix:
            type: stream
            path: "%kernel.logs_dir%/alarm_zabbix.log"
            channels: ["alarm_zabbix"]
        bitrix_create:
            type: stream
            path: "%kernel.logs_dir%/bitrix_create.log"
            channels: ["bitrix_create"]
        one_s:
            type: stream
            path: "%kernel.logs_dir%/1s.log"
            channels: ["one_s"]