monolog:
    channels: ["sms", "alarm_zabbix", "bitrix_create"]
    handlers:
        sms:
            type: stream
            path: "%kernel.logs_dir%/sms.log"
            channels: ["sms"]
        alarm_zabbix:
            type: stream
            path: "%kernel.logs_dir%/alarm_zabbix.log"
            channels: ["alarm_zabbix"]
        bitrix_create:
            type: stream
            path: "%kernel.logs_dir%/bitrix_create.log"
            channels: ["bitrix_create"]