monolog:
    channels: ["sms", "zabbix", "bitrix", "one_s"]
    handlers:
        sms:
            type: stream
            path: "%kernel.logs_dir%/sms.log"
            channels: ["sms"]
        alarm_zabbix:
            type: stream
            path: "%kernel.logs_dir%/alarm_zabbix.log"
            channels: ["zabbix"]
        bitrix_create:
            type: stream
            path: "%kernel.logs_dir%/bitrix_create.log"
            channels: ["bitrix"]
        one_s:
            type: stream
            path: "%kernel.logs_dir%/1s.log"
            channels: ["one_s"]