security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER: ~
        ROLE_SUPPORT: [ROLE_INTERCOMS]
        ROLE_MODERATOR: [ROLE_PHONE_MODERATOR, ROLE_ORDER_MODERATOR, ROLE_INTERCOMS_MODERATOR]
        ROLE_ADMIN: [ROLE_SUPPORT, ROLE_MODERATOR, ROLE_SMS_ADMINISTRATOR]
        ROLE_KNOWLEDGE_BASE_MODERATOR: ~
        ROLE_INTERCOMS: ~
        ROLE_SMS_ADMINISTRATOR: ~
        ROLE_USERS_ADMINISTRATOR: ~
        ROLE_CHANGE_ORDER_EXECUTOR: ~

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        #in_memory: { memory: ~ }
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            #                always_use_default_target_path: false
            #                default_target_path:            /login/redirect/
            logout:       true
            anonymous:    true
            remember_me:
                secret:      "%kernel.secret%"
                lifetime: 604800
                path:     /
                domain:   ~
                user_provider: fos_userbundle

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/app/intercom-task, role: ROLE_SUPPORT }
        - { path: ^/admin/app/sms-smstemplate, role: ROLE_SMS_ADMINISTRATOR }
        - { path: ^/admin/, role: ROLE_ADMIN }