parameters:
    ssh:
        servers:
            66: 'BUZ'
            67: 'DEDOVSK'
            68: 'DEDOVSK'
            35: 'DEDOVSK'
            34: 'DEDOVSK'
            58: 'DB'
            52: 'GLEB'
            53: 'SNEG'
            62: 'GLEB'
            49: 'GREEN'
            60: 'KOTEL'
            57: 'MAN'
            55: 'NUTR'
            59: 'IPK'
            61: 'AGRO'
            54: 'SHNYR'
            27: 'SOUTH'
            50: 'VEI'
            26: 'GIDRO'
            40: 'A@'
            39: 'A@'
            44: 'L$'
            45: 'L$'
            37: 'L%'
            48: 'SNEG'
            51: 'SLOB'
        prefix: '%ssh_password_prefix%'
        suffix: '%ssh_password_suffix%'
        user: '%ssh_user%'
